server:
  port: 8081

dubbo:
  registry:
    address: zookeeper://172.18.0.6:2181
    timeout: 10000
  scan:
    base-packages: org.dataochen.service
  protocol:
    port: 20882
    name: dubbo
  provider:
    threads: 300
    loadbalance: roundrobin
    timeout: 8000
    version: 1.0
  consumer:
    loadbalance: roundrobin
    timeout: 3000
    retries: 0
  application:
    id: docker_demo_web
spring:
  rabbitmq:
    addresses: 172.18.0.8:5672
    publisher-returns: true
    publisher-confirm-type: SIMPLE
    connection-timeout: 1500
    listener:
      simple:
        retry:
          max-attempts: 3
          max-interval: 2000
          enabled: true
        default-requeue-rejected: true
    username: guest
    password: guest